[project]
name = "pyorganizer"
version = "0.1.0"
description = "Bot organizador de archivos inteligente"
authors = [
    {name = "Lu1s2556", email = "luiserojasp06@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "watchdog (==4.0.0)",
    "python-dateutil (==2.9.0)",
    "pyside6 (==6.8.1)", # Versión estable actual para 3.12
    "scikit-learn (==1.5.2)",
    "textblob (==0.17.1)",
    "nltk (>=3.9.1)", # Corregido de nlkt a nltk y versión compatible
    "fasttext-wheel (>=0.9.2,<0.10.0)"
]

[tool.poetry]
# Esta línea es la que evita el error de "No file/folder found"
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"