[project]
name = "pyorganizer"
version = "0.1.0"
description = "Bot gestor de archivos en segund plano"
authors = [
    {name = "Lu1s2556",email = "luiserojasp06@gmail.com"}
]
requires-python = "3.12.7"
dependencies = [
    "pyside6 (==6.10.0)",
    "watchdog (==4.0.0)",
    "python-dateutil (==2.9.0)",
    "textblob (==0.17.1)",
    "scikit-learn (==1.5.2)",
    "nltk (==3.8.1)",
    "pywin32 (==306)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
